# General channel settings
site_name: "Tsuki Chan"
description: "A simple image board engine."
allowed_file_types:
  - jpg
  - png
  - webp
theme: "tsuki-dark.css"

# Database settings, you probably don't need to touch these.
database:
  type: "sqlite"
  uploads: "database/uploads"
  path: "database/tsuki.db"